### PR TITLE
Update subject mention syntax prefix

### LINKED ISSUE #11: Incorrect matches
https://github.com/zooniverse-ui/markdownz/blob/master/src/components/markdown.js#L44

https://github.com/zooniverse-ui/markdownz/blob/master/src/components/markdown.js#L46

Talk does not match subject mentions like this.  The syntax for matching a subject is `^S<id>`, e.g. `^S123`.

Likewise collection mentions are `^C<id>`.

The best way to handle this in terms of front-end links would probably be to add a redirect route at /talk/subjects/:id that looks up the project slug and redirects to the project route.

### PR DESCRIPTION
**Pull request by aweiksnar**
- Adds a prefix 'S' character for subject mentions
- closes #11

### CODE REVIEW

**Comment by aweiksnar** [comment]
@parrish How does this look for matching subject links on the backend? I think it would satisfy the current `S` prefix matching, but would require the addition of the project-specified matching schema to the API

**Comment by parrish** [comment]
That looks pretty consistent.  Talk still doesn't accept the extremely explicit @username/project-name^S123 format though.  I'll ticket up an issue for that.

**Comment by parrish** [comment]
Just to double check, the motivation for the verbose format is to disambiguate between the same subject being used in multiple projects, correct?

Do we actually care about that in terms of talk?  I can't imagine cases where you'd want to hide other discussions about the same subject.  It feels like we're just trying to cram that in there because of our route structure on the frontend.

**Comment by edpaget** [comment]
I think we do. Most of the time the simple form will work just fine for identifying a subject you're talking about, but if you want to link to the discussion of a Subject in another project, it gives you a shorthand for it.

**Comment by parrish** [comment]
My point is that the shorthand of @username/project-name^S123 is just ^S123.  Subject id: 123.

If that subject is used in multiple projects, we shouldn't try to hide the discussions about it from other projects.  So what's the point of trying to specify who owns the project and what that project name is in the markup?

**Comment by edpaget** [comment]
I thought Subject Pages were going to be per-project. So if you want to link to the page that has all the tags and discussions from one project you'd need to specify that.

**Comment by parrish** [comment]
If that's the case then the thing being discussed is the set-member-subject rather than the subject.  We should just use that id in lieu of the subject id.

**Comment by edpaget** [comment]
Why?

**Comment by parrish** [comment]
If talk is only going to refer to the per-project subject, rather than the subject as itself, we should just use the id of the thing that actually identifies the per-project subject. e.g. the set-member-subject id.

It seems pretty silly to use an ambiguous identifier, then work around it by packing extra markup in.

**Comment by edpaget** [comment]
In every project talk linking to ^S123123 will take you to the Project's page for the referenced. The extra markup is only for cross-project references where being explicit that you are referencing a subject page from another project make total sense to me. 

Also the design of subjects page is under active discussion as far as I am aware, so it may be moot and there may just be a single global subjects page.

**Comment by parrish** [comment]
Yep, we should get some design direction here first

**Pull request merged**
