### PR TITLE
Add the image-size plugin

### PR DESCRIPTION
**Pull request by parrish**
`original size`

original size

Adds:

`specified width`
`specified width and height`

### CODE REVIEW

**Comment by parrish** [comment]
Hmm... one sec....

**Comment by parrish** [comment]
Definitely works better without typos.  On the other hand, your CI setup looks broken:

```
Zuul tried to run tests in saucelabs, however no saucelabs credentials were provided.
```

**Comment by edpaget** [comment]
I don't think the encrypted credentials work across Forks.

**Comment by edpaget** [comment]
Will be released as 2.6.0

**Comment by edpaget** [comment]
Whoops 2.5.0

**Comment by parrish** [comment]
Ah, cool.  Tried running them from a new account and saucelab doesn't seem to connect to the panoptes api (everything times out).

**Comment by edpaget** [comment]
Yeah SauceLabs is a little flakey generally, but is too useful to get rid of. Things were passing on it about an hour ago.

**Pull request merged**
