### PR TITLE
secure links and move to zoo logo from github

### LINKED ISSUE #33: Example image is broken
https://github.com/zooniverse-ui/markdownz/blob/master/src/lib/markdown-insert.js#L33

That image doesn't exist on S3. When we fix it we should also make sure to use an https URL to avoid a mixed content warning.

### PR DESCRIPTION
**Pull request by camallen**
closes #33

### CODE REVIEW

**Comment by camallen** [comment]
seems the sauce labs creds / integration is missing..?
```
> markdownz@4.0.3 test-sauce /home/travis/build/zooniverse-ui/markdownz
> zuul -- test/**/*.js
Error:
Zuul tried to run tests in saucelabs, however no saucelabs credentials were provided.
See the zuul wiki (https://github.com/defunctzombie/zuul/wiki/Cloud-testing) for info on how to setup cloud testing.
```

**Comment by marten** [comment]
Maybe because it's a PR from your github to this one. LGTM, shall we just hope it sorts itself out after merge? Seems unlikely it's related to this commit anyways, so I'm fine with just merging.

**Comment by camallen** [comment]
Yeah - i didn't have access to the env vars via the travis run, https://github.com/defunctzombie/zuul/issues/86. Something to note for future PRs from forks.

**Comment by brian-c** [comment]
Published as 4.0.4.

**Comment by camallen** [comment]
:+1:

**Pull request merged**
